import {
  FiActivity,
  FiAlertCircle,
  FiArrowUp,
  FiArrowUpRight,
  FiAward,
  FiBookOpen,
  FiBox,
  FiCheck,
  FiCloud,
  FiCode,
  FiCpu,
  FiDatabase,
  FiDownload,
  FiFileText,
  FiGithub,
  FiGitBranch,
  FiGlobe,
  FiImage,
  FiLayers,
  FiLinkedin,
  FiLoader,
  FiMail,
  FiMapPin,
  FiMenu,
  FiMonitor,
  FiMessageSquare,
  FiMoon,
  FiPhone,
  FiRadio,
  FiSearch,
  FiServer,
  FiShield,
  FiSun,
  FiTerminal,
  FiTool,
  FiZap,
  FiX,
} from 'react-icons/fi'

/**
 * Registro de íconos: los archivos de contenido (`.yaml`) sólo escriben el
 * nombre (`icon: cloud`) y aquí se traduce al componente correspondiente.
 */
export const ICONS = {
  activity: FiActivity,
  alert: FiAlertCircle,
  arrowUp: FiArrowUp,
  arrowUpRight: FiArrowUpRight,
  award: FiAward,
  book: FiBookOpen,
  box: FiBox,
  check: FiCheck,
  cloud: FiCloud,
  code: FiCode,
  cpu: FiCpu,
  database: FiDatabase,
  devops: FiGitBranch,
  document: FiFileText,
  download: FiDownload,
  email: FiMail,
  github: FiGithub,
  chat: FiMessageSquare,
  globe: FiGlobe,
  image: FiImage,
  layers: FiLayers,
  linkedin: FiLinkedin,
  loader: FiLoader,
  location: FiMapPin,
  menu: FiMenu,
  monitor: FiMonitor,
  moon: FiMoon,
  phone: FiPhone,
  radio: FiRadio,
  search: FiSearch,
  server: FiServer,
  shield: FiShield,
  sun: FiSun,
  terminal: FiTerminal,
  tool: FiTool,
  zap: FiZap,
  close: FiX,
}

/** Devuelve el ícono pedido; si el nombre no existe cae en uno neutro. */
export function getIcon(name) {
  return ICONS[name] ?? ICONS.layers
}
